### ISSUE TITLE
gost_x509_xml branch build failed

### ISSUE THREAD

**Issue by Demonell** [CryptoPro/corefx#13]
I have loaded gost_x509_xml branch using git command:
git clone --single-branch --branch gost_x509_xml https://github.com/CryptoProLLC/corefx.git

Then I moved to corefx directory and run build.cmd. It throws six errors;
![image](https://user-images.githubusercontent.com/22554521/66748624-53320880-ee90-11e9-9425-251faafb53ec.png)

**Comment by Fasjeit** [comment]
You need to copy patched netstandard libraries to your local nuget package cache [from here](https://github.com/CryptoProLLC/NetStandard.Library).
  
You can do this by using this script:
```yaml
  - cmd: git clone https://github.com/CryptoProLLC/NetStandard.Library
  - ps: New-Item -ItemType Directory -Force -Path "$env:userprofile\.nuget\packages\netstandard.library"
  - ps: Copy-Item -Force -Recurse ".\NetStandard.Library\nugetReady\netstandard.library" -Destination "$env:userprofile\.nuget\packages\"
```
